version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    depends_on:
      - postgres
      - mailpit
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/assignment_five
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: assignment_five
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port

volumes:
  postgres_data:
  maven-repo: